"""your message

Revision ID: b51794263db6
Revises: 0bbc02026770
Create Date: 2025-09-16 00:57:20.257715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51794263db6'
down_revision = '0bbc02026770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
